apiVersion: v1
kind: Service
metadata:
  name: f1-telemetry-app
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: f1-telemetry-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: {{ .Values.service.type }}
